# Generated by Django 4.0.6 on 2022-07-25 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.staff'),
        ),
    ]
