# Generated by Django 4.0.6 on 2022-07-25 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_orderservice_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
        ),
        migrations.RenameModel(
            old_name='OrderService',
            new_name='Service',
        ),
        migrations.DeleteModel(
            name='OrderServiceItem',
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='store.service'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceitem',
            unique_together={('service', 'product')},
        ),
    ]
